service_package_filtered_objects:
  - CryptoIDCred
  - CryptoValCred
  - CryptoKey
  - CryptoProfile
  - SSLProxyProfile
  - CryptoCertificate
  - SSLClientProfile
  - SSLServerProfile
  - JWTGenerator
  - JWTValidator
  - file
