namespace: community

name: datapower

version: 1.0.0

readme: README.md

authors:
- Anthony Schneider tonyschndr@gmail.com

description: |
  The Ansible DataPower collection includes a variety of modules to automate
  the management of IBM DataPower Appliances.

license:
- GPL-2.0-or-later

license_file: 'LICENSE'

tags:
  - ibm
  - datapower
  - community
  - network

dependencies:
  ansible.netcommon: '>=2.4.0'

repository: https://github.com/Br35Ba56/ansible-datapower
documentation: ''
homepage: https://github.com/Br35Ba56/ansible-datapower
issues: https://github.com/Br35Ba56/ansible-datapower

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml