namespace: br35ba56

name: datapower

version: 1.0.2

readme: README.md

authors:
- Anthony Schneider tonyschndr@gmail.com

description: |
  The Ansible DataPower collection includes a variety of modules to automate
  the management of IBM DataPower Appliances.

license_file: 'LICENSE'

tags:
  - ibm
  - datapower
  - community
  - network

dependencies:
  ansible.netcommon: '>=2.4.0'

repository: https://github.com/Br35Ba56/ansible-datapower
documentation: https://br35ba56.github.io/ansible-datapower/
homepage: https://github.com/Br35Ba56/ansible-datapower
issues: https://github.com/Br35Ba56/ansible-datapower

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - codecov.yml
  - .github
  - venv 
