galaxy_info:
  author: Tony Schneider
  description: Create a Crypto Validation Credential on IBM DataPower
  company: ""
  role_name: crypto_val_cred
  namespace: br35ba56

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
  - name: DataPower
    versions:
    - 10.0.1.4

  galaxy_tags:
    - datapower
    - ibm
    - community
    - network

dependencies: []
