---
- name: Converge
  connection: local
  hosts: all

  tasks:
    - name: Execute role
      include_role:
        name: dp_private_key
      vars:
        key_src:  "{{ private_key_path }}"
        key_dest:  "/cert/{{ private_key_path | basename }}"
        key_name: "{{ private_key_path | basename | replace('.pem', '') }}"
        password: "{{ passphrase }}"
        password_alias_name: "priv_key_pw_alias"