---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
  - name: Get CryptoCertificate
    br35ba56.datapower.get_config:
      class_name: CryptoCertificate
      domain: "{{ domain_name }}"
      status: yes
    register: crypto_cert

  - name: Check the ID Cred is in an up state
    assert:
      that: "'up' in crypto_cert.response.CryptoCertificate.state.opstate"
