- name: Quiescing "{{ dp_group }}" DataPowers
  community.datapower.action:
    domain: default
    action: QuiesceDP
    parameters:
      timeout: "{{ timeout }}"
  when:  dp_group  in group_names

- name: Pause for "{{ timeout }}" seconds
  pause:
    seconds: "{{ timeout }}"
