---
- name: Create Crypto Identification Credentials
  br35ba56.datapower.config:
    state: merged
    domain: "{{ domain_name }}"
    config:
      CryptoIdentCred:
        Certificate:
          value: "{{ cert_name }}"
        Key:
          value: "{{ key_name }}"
        mAdminState: enabled
        name: "{{ crypto_id_cred_name }}"
