# Borrowed from https://github.com/ansible-collections/community.datapower/blob/master/.github/workflows/documentation.yml

name: documentation

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ansible_collections/community/datapower
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path:  ansible_collections/community/datapower

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install ansible-base (devel)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Build collection
        run: ansible-galaxy collection build .

      - name: Install collection
        run: ansible-galaxy collection install community-datapower-*.tar.gz

      - name: Install ansible-doc-extractor
        run: pip install wheel setuptools git+https://github.com/xlab-steampunk/ansible-doc-extractor.git --upgrade

      - name: Install rstdoc
        run: pip install -v rstdoc

      - name: Create docs dir
        run: mkdir -p docs/{httpapi,}

      - name: Create rst files from modules
        run: ansible-doc-extractor ./docs plugins/modules/*.py

#       - name: Create rst files from httpapi
#         run: ansible-doc-extractor ./docs/lookup plugins/httpapi/rest_mgmt.py

      - name: Create collection index document
        run: |
          echo "# Datapower Ansible Collection Documentation" > docs/index.md
          echo "## Modules" >> docs/index.md
          find plugins/modules -type f -name '*.py' -exec bash -c 'echo "- [$(basename "{}" ".py")]($(basename {} .py).html)"' \; >> docs/index.md
          # echo "## httpapi" >> docs/index.md
          # find plugins/httapi -type f -name '*.py' -exec bash -c 'echo "- [$(basename "{}" ".py")](httpapi/$(basename {} .py).html)"' \; >> docs/index.md

      - name: Create module html documents from rst files
        run: |
          find ./docs -type f -name '*.rst' -maxdepth 1 -exec bash -c 'rstdoc {} "docs/$(basename "{}" ".rst").html" rst_html' \;
#       - name: Create httpapi html documents from rst files
#         run: |
#           find ./docs/lookup -type f -name '*.rst' -maxdepth 1 -exec bash -c 'rstdoc {} "docs/httpapi/$(basename "{}" ".rst").html" rst_html' \;

      - name: Remove intermediary rst docs
        run: find docs/ -name '*.rst' -delete

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ansible_collections/community/datapower/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
